export * from './auth.model';
export * from './hocsinh.model';
export * from './backup.model';
export * from './ethnicity.model';
export * from './religion.model';
export * from './occupation.model';
export * from './user-management.model';
export * from './grade.model';
export * from './semester.model';
