// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220061449_Avarager")]
    partial class Avarager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.AcademicPerformance", b =>
                {
                    b.Property<string>("AcademicPerformanceId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("AcademicPerformanceId");

                    b.Property<string>("AcademicPerformanceName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("AcademicPerformanceName");

                    b.HasKey("AcademicPerformanceId");

                    b.ToTable("ACADEMIC_PERFORMANCE");
                });

            modelBuilder.Entity("API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccountSetupToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccountSetupTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FaceDescriptor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FaceEnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccountSetupComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFaceEnrolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ScheduledDeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Models.BackupSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BackupSchedules");
                });

            modelBuilder.Entity("API.Models.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ClassName");

                    b.Property<int>("ClassSize")
                        .HasColumnType("integer")
                        .HasColumnName("ClassSize");

                    b.Property<string>("GradeLevelId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("GradeLevelId");

                    b.Property<string>("SchoolYearId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("TeacherId");

                    b.HasKey("ClassId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CLASS");
                });

            modelBuilder.Entity("API.Models.ClassAssignment", b =>
                {
                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("GradeLevelId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("GradeLevelId");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("StudentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.HasKey("SchoolYearId", "GradeLevelId", "ClassId", "StudentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("StudentId");

                    b.ToTable("CLASS_ASSIGNMENT");
                });

            modelBuilder.Entity("API.Models.ClassSemesterResult", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SemesterId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer")
                        .HasColumnName("PassCount");

                    b.Property<decimal>("PassRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PassRate");

                    b.HasKey("ClassId", "SchoolYearId", "SemesterId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.ToTable("CLASS_SEMESTER_RESULT");
                });

            modelBuilder.Entity("API.Models.ClassSubjectResult", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.Property<string>("SemesterId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer")
                        .HasColumnName("PassCount");

                    b.Property<decimal>("PassRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PassRate");

                    b.HasKey("ClassId", "SchoolYearId", "SubjectId", "SemesterId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("CLASS_SUBJECT_RESULT");
                });

            modelBuilder.Entity("API.Models.Conduct", b =>
                {
                    b.Property<string>("ConductId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ConductId");

                    b.Property<string>("ConductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ConductName");

                    b.HasKey("ConductId");

                    b.ToTable("CONDUCT");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DepartmentName");

                    b.Property<string>("HeadTeacherId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("HeadTeacherId");

                    b.HasKey("DepartmentId");

                    b.HasIndex("HeadTeacherId");

                    b.ToTable("DEPARTMENT");
                });

            modelBuilder.Entity("API.Models.Ethnicity", b =>
                {
                    b.Property<string>("EthnicityId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("EthnicityId");

                    b.Property<string>("EthnicityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("EthnicityName");

                    b.HasKey("EthnicityId");

                    b.ToTable("ETHNICITY");
                });

            modelBuilder.Entity("API.Models.Grade", b =>
                {
                    b.Property<int>("RowNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RowNumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowNumber"));

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("Comment")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Comment");

                    b.Property<string>("GradeTypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("GradeTypeId");

                    b.Property<bool>("IsComment")
                        .HasColumnType("boolean")
                        .HasColumnName("IsComment");

                    b.Property<string>("SchoolYearId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Score");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.HasKey("RowNumber");

                    b.HasIndex("ClassId");

                    b.HasIndex("GradeTypeId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("GRADE");
                });

            modelBuilder.Entity("API.Models.GradeLevel", b =>
                {
                    b.Property<string>("GradeLevelId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("GradeLevelId");

                    b.Property<string>("GradeLevelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("GradeLevelName");

                    b.HasKey("GradeLevelId");

                    b.ToTable("GRADE_LEVEL");
                });

            modelBuilder.Entity("API.Models.GradeType", b =>
                {
                    b.Property<string>("GradeTypeId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("GradeTypeId");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer")
                        .HasColumnName("Coefficient");

                    b.Property<string>("GradeTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("GradeTypeName");

                    b.HasKey("GradeTypeId");

                    b.ToTable("GRADE_TYPE");
                });

            modelBuilder.Entity("API.Models.Occupation", b =>
                {
                    b.Property<string>("OccupationId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("OccupationId");

                    b.Property<string>("OccupationName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("OccupationName");

                    b.HasKey("OccupationId");

                    b.ToTable("OCCUPATION");
                });

            modelBuilder.Entity("API.Models.Regulation", b =>
                {
                    b.Property<int>("MaxClassSize")
                        .HasColumnType("integer")
                        .HasColumnName("MaxClassSize");

                    b.Property<int>("MinClassSize")
                        .HasColumnType("integer")
                        .HasColumnName("MinClassSize");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer")
                        .HasColumnName("PassingScore");

                    b.ToTable("REGULATION");
                });

            modelBuilder.Entity("API.Models.Religion", b =>
                {
                    b.Property<string>("ReligionId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ReligionId");

                    b.Property<string>("ReligionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ReligionName");

                    b.HasKey("ReligionId");

                    b.ToTable("RELIGION");
                });

            modelBuilder.Entity("API.Models.Result", b =>
                {
                    b.Property<string>("ResultId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ResultId");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ResultName");

                    b.HasKey("ResultId");

                    b.ToTable("RESULT");
                });

            modelBuilder.Entity("API.Models.SchoolYear", b =>
                {
                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SchoolYearName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SchoolYearName");

                    b.HasKey("SchoolYearId");

                    b.ToTable("SCHOOL_YEAR");
                });

            modelBuilder.Entity("API.Models.Semester", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer")
                        .HasColumnName("Coefficient");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SemesterName");

                    b.HasKey("SemesterId");

                    b.ToTable("SEMESTER");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Email");

                    b.Property<string>("EthnicityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("EthnicityId");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("FatherName");

                    b.Property<string>("FatherOccupationId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("FatherOccupationId");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("FullName");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean")
                        .HasColumnName("Gender");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("MotherName");

                    b.Property<string>("MotherOccupationId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("MotherOccupationId");

                    b.Property<string>("ReligionId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ReligionId");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.HasKey("StudentId");

                    b.HasIndex("EthnicityId");

                    b.HasIndex("FatherOccupationId");

                    b.HasIndex("MotherOccupationId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("UserId");

                    b.ToTable("STUDENT");
                });

            modelBuilder.Entity("API.Models.StudentSemesterResult", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SemesterId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<string>("AcademicPerformanceId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("AcademicPerformanceId");

                    b.Property<decimal>("AverageSemester")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageSemester");

                    b.Property<string>("ConductId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ConductId");

                    b.HasKey("StudentId", "ClassId", "SchoolYearId", "SemesterId");

                    b.HasIndex("AcademicPerformanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ConductId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.ToTable("STUDENT_SEMESTER_RESULT");
                });

            modelBuilder.Entity("API.Models.StudentSubjectResult", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.Property<string>("SemesterId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("SemesterId");

                    b.Property<decimal>("Average15Min")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Average15Min");

                    b.Property<decimal>("Average45Min")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Average45Min");

                    b.Property<decimal>("AverageOral")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageOral");

                    b.Property<decimal>("AverageSemester")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageSemester");

                    b.Property<decimal>("ExamScore")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ExamScore");

                    b.HasKey("StudentId", "ClassId", "SchoolYearId", "SubjectId", "SemesterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("STUDENT_SUBJECT_RESULT");
                });

            modelBuilder.Entity("API.Models.StudentYearResult", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("StudentId");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("AcademicPerformanceId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("AcademicPerformanceId");

                    b.Property<decimal>("AverageSemester1")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageSemester1");

                    b.Property<decimal>("AverageSemester2")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageSemester2");

                    b.Property<decimal>("AverageYear")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("AverageYear");

                    b.Property<string>("ConductId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ConductId");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ResultId");

                    b.HasKey("StudentId", "ClassId", "SchoolYearId");

                    b.HasIndex("AcademicPerformanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ConductId");

                    b.HasIndex("ResultId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("STUDENT_YEAR_RESULT");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer")
                        .HasColumnName("Coefficient");

                    b.Property<int>("LessonCount")
                        .HasColumnType("integer")
                        .HasColumnName("LessonCount");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SubjectName");

                    b.HasKey("SubjectId");

                    b.ToTable("SUBJECT");
                });

            modelBuilder.Entity("API.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("TeacherId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Address");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("TeacherName");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.HasKey("TeacherId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TEACHER");
                });

            modelBuilder.Entity("API.Models.TeachingAssignment", b =>
                {
                    b.Property<int>("RowNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RowNumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowNumber"));

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ClassId");

                    b.Property<string>("SchoolYearId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SchoolYearId");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("SubjectId");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("TeacherId");

                    b.HasKey("RowNumber");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TEACHING_ASSIGNMENT");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Models.Class", b =>
                {
                    b.HasOne("API.Models.GradeLevel", "GradeLevel")
                        .WithMany("Classes")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId");

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("API.Models.ClassAssignment", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.GradeLevel", "GradeLevel")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.ClassSemesterResult", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("ClassSemesterResults")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("ClassSemesterResults")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Semester", "Semester")
                        .WithMany("ClassSemesterResults")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("API.Models.ClassSubjectResult", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("ClassSubjectResults")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("ClassSubjectResults")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Semester", "Semester")
                        .WithMany("ClassSubjectResults")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("ClassSubjectResults")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.HasOne("API.Models.Teacher", "HeadTeacher")
                        .WithMany()
                        .HasForeignKey("HeadTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadTeacher");
                });

            modelBuilder.Entity("API.Models.Grade", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("Grades")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.GradeType", "GradeType")
                        .WithMany("Grades")
                        .HasForeignKey("GradeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("Grades")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Semester", "Semester")
                        .WithMany("Grades")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GradeType");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.HasOne("API.Models.Ethnicity", "Ethnicity")
                        .WithMany("Students")
                        .HasForeignKey("EthnicityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Occupation", "FatherOccupation")
                        .WithMany("StudentFathers")
                        .HasForeignKey("FatherOccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Occupation", "MotherOccupation")
                        .WithMany("StudentMothers")
                        .HasForeignKey("MotherOccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Religion", "Religion")
                        .WithMany("Students")
                        .HasForeignKey("ReligionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Ethnicity");

                    b.Navigation("FatherOccupation");

                    b.Navigation("MotherOccupation");

                    b.Navigation("Religion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.StudentSemesterResult", b =>
                {
                    b.HasOne("API.Models.AcademicPerformance", "AcademicPerformance")
                        .WithMany()
                        .HasForeignKey("AcademicPerformanceId");

                    b.HasOne("API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Conduct", "Conduct")
                        .WithMany()
                        .HasForeignKey("ConductId");

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPerformance");

                    b.Navigation("Class");

                    b.Navigation("Conduct");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.StudentSubjectResult", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("StudentSubjectResults")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("StudentSubjectResults")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Semester", "Semester")
                        .WithMany("StudentSubjectResults")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("StudentSubjectResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("StudentSubjectResults")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.StudentYearResult", b =>
                {
                    b.HasOne("API.Models.AcademicPerformance", "AcademicPerformance")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("AcademicPerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Conduct", "Conduct")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("ConductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Result", "Result")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("StudentYearResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPerformance");

                    b.Navigation("Class");

                    b.Navigation("Conduct");

                    b.Navigation("Result");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.Teacher", b =>
                {
                    b.HasOne("API.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.TeachingAssignment", b =>
                {
                    b.HasOne("API.Models.Class", "Class")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SchoolYear", "SchoolYear")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Teacher", "Teacher")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.AcademicPerformance", b =>
                {
                    b.Navigation("StudentYearResults");
                });

            modelBuilder.Entity("API.Models.Class", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("ClassSemesterResults");

                    b.Navigation("ClassSubjectResults");

                    b.Navigation("Grades");

                    b.Navigation("StudentSubjectResults");

                    b.Navigation("StudentYearResults");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("API.Models.Conduct", b =>
                {
                    b.Navigation("StudentYearResults");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("API.Models.Ethnicity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("API.Models.GradeLevel", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("API.Models.GradeType", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("API.Models.Occupation", b =>
                {
                    b.Navigation("StudentFathers");

                    b.Navigation("StudentMothers");
                });

            modelBuilder.Entity("API.Models.Religion", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("API.Models.Result", b =>
                {
                    b.Navigation("StudentYearResults");
                });

            modelBuilder.Entity("API.Models.SchoolYear", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("ClassSemesterResults");

                    b.Navigation("ClassSubjectResults");

                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("StudentSubjectResults");

                    b.Navigation("StudentYearResults");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("API.Models.Semester", b =>
                {
                    b.Navigation("ClassSemesterResults");

                    b.Navigation("ClassSubjectResults");

                    b.Navigation("Grades");

                    b.Navigation("StudentSubjectResults");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("Grades");

                    b.Navigation("StudentSubjectResults");

                    b.Navigation("StudentYearResults");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjectResults");

                    b.Navigation("Grades");

                    b.Navigation("StudentSubjectResults");

                    b.Navigation("Teachers");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("API.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TeachingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
